// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBVJI_WEYVFxJSI9PP-KjBYl8hL5n1C6oM',
//     appId: '1:593861404577:web:c9bdacfe59a05c7c58cde0',
//     messagingSenderId: '593861404577',
//     projectId: 'plot-app-b8799',
//     authDomain: 'plot-app-b8799.firebaseapp.com',
//     storageBucket: 'plot-app-b8799.firebasestorage.app',
//     measurementId: 'G-1GKW637MKS',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAxzFiDYcpW51PF8SDC3u71SdiFi1RYMW0',
//     appId: '1:593861404577:android:9b993b67cc89e33758cde0',
//     messagingSenderId: '593861404577',
//     projectId: 'plot-app-b8799',
//     storageBucket: 'plot-app-b8799.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD618YkPPC2SreBI-zEvlyS2trQBvkQGZo',
//     appId: '1:593861404577:ios:b401fa3244aaf43258cde0',
//     messagingSenderId: '593861404577',
//     projectId: 'plot-app-b8799',
//     storageBucket: 'plot-app-b8799.firebasestorage.app',
//     iosBundleId: 'com.example.plotApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD618YkPPC2SreBI-zEvlyS2trQBvkQGZo',
//     appId: '1:593861404577:ios:b401fa3244aaf43258cde0',
//     messagingSenderId: '593861404577',
//     projectId: 'plot-app-b8799',
//     storageBucket: 'plot-app-b8799.firebasestorage.app',
//     iosBundleId: 'com.example.plotApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBVJI_WEYVFxJSI9PP-KjBYl8hL5n1C6oM',
//     appId: '1:593861404577:web:b0a5ceeb3dc8a22758cde0',
//     messagingSenderId: '593861404577',
//     projectId: 'plot-app-b8799',
//     authDomain: 'plot-app-b8799.firebaseapp.com',
//     storageBucket: 'plot-app-b8799.firebasestorage.app',
//     measurementId: 'G-JY24LSMSV1',
//   );

// }



    // File generated by FlutterFire CLI.
    // ignore_for_file: type=lint
    import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
    import 'package:flutter/foundation.dart'
        show defaultTargetPlatform, kIsWeb, TargetPlatform;

    /// Default [FirebaseOptions] for use with your Firebase apps.
    ///
    /// Example:
    /// ```dart
    /// import 'firebase_options.dart';
    /// // ...
    /// await Firebase.initializeApp(
    ///   options: DefaultFirebaseOptions.currentPlatform,
    /// );
    /// ```
    class DefaultFirebaseOptions {
      static FirebaseOptions get currentPlatform {
        if (kIsWeb) {
          // Keep old web settings unless you have new ones for plot-app-734f3
          return web;
        }
        switch (defaultTargetPlatform) {
          case TargetPlatform.android:
            // Use NEWEST Android settings for plot-app-734f3
            return android;
          case TargetPlatform.iOS:
            // Keep old iOS settings unless you have new ones for plot-app-734f3
            // If you have a GoogleService-Info.plist for plot-app-734f3, update these too.
            return ios;
          case TargetPlatform.macOS:
            // Keep old macOS settings unless you have new ones for plot-app-734f3
            return macos;
          case TargetPlatform.windows:
             // Keep old windows settings unless you have new ones for plot-app-734f3
            return windows;
          case TargetPlatform.linux:
            throw UnsupportedError(
              'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
            );
          default:
            throw UnsupportedError(
              'DefaultFirebaseOptions are not supported for this platform.',
            );
        }
      }

      // Old Web settings (plot-app-b8799) - Replace if you have new ones for plot-app-734f3
      static const FirebaseOptions web = FirebaseOptions(
        apiKey: 'AIzaSyBVJI_WEYVFxJSI9PP-KjBYl8hL5n1C6oM', // Replace if needed
        appId: '1:593861404577:web:c9bdacfe59a05c7c58cde0', // Replace if needed
        messagingSenderId: '593861404577', // Replace if needed
        projectId: 'plot-app-b8799', // Replace if needed
        authDomain: 'plot-app-b8799.firebaseapp.com', // Replace if needed
        storageBucket: 'plot-app-b8799.firebasestorage.app', // Replace if needed
        measurementId: 'G-1GKW637MKS', // Replace if needed
      );

      // ✅✅ --- NEWEST Android settings (plot-app-734f3) --- ✅✅
      static const FirebaseOptions android = FirebaseOptions(
        apiKey: 'AIzaSyAtST0wZ8MIy7x1-daPGdfhCth00EkRP2o', // from google-services (14).json
        appId: '1:1011063796547:android:0c0f57e01882ffa0d075f6', // from google-services (14).json
        messagingSenderId: '1011063796547', // from google-services (14).json
        projectId: 'plot-app-734f3', // from google-services (14).json
        storageBucket: 'plot-app-734f3.firebasestorage.app', // from google-services (14).json
      );
      // ✅✅ --- End of NEWEST Android settings --- ✅✅


      // Old iOS settings (plot-app-b8799) - Replace if you have the corresponding GoogleService-Info.plist for plot-app-734f3
      static const FirebaseOptions ios = FirebaseOptions(
        apiKey: 'AIzaSyD618YkPPC2SreBI-zEvlyS2trQBvkQGZo', // Replace if needed
        appId: '1:593861404577:ios:b401fa3244aaf43258cde0', // Replace if needed
        messagingSenderId: '593861404577', // Replace if needed
        projectId: 'plot-app-b8799', // Replace if needed
        storageBucket: 'plot-app-b8799.firebasestorage.app', // Replace if needed
        iosBundleId: 'com.example.plotApp', // Make sure this matches your actual iOS Bundle ID
      );

      // Old macOS settings (plot-app-b8799) - Replace if needed
      static const FirebaseOptions macos = FirebaseOptions(
        apiKey: 'AIzaSyD618YkPPC2SreBI-zEvlyS2trQBvkQGZo', // Replace if needed
        appId: '1:593861404577:ios:b401fa3244aaf43258cde0', // Replace if needed
        messagingSenderId: '593861404577', // Replace if needed
        projectId: 'plot-app-b8799', // Replace if needed
        storageBucket: 'plot-app-b8799.firebasestorage.app', // Replace if needed
        iosBundleId: 'com.example.plotApp', // Make sure this matches your actual macOS Bundle ID
      );

      // Old Windows settings (plot-app-b8799) - Replace if needed
       static const FirebaseOptions windows = FirebaseOptions(
         apiKey: 'AIzaSyBVJI_WEYVFxJSI9PP-KjBYl8hL5n1C6oM', // Replace if needed
         appId: '1:593861404577:web:b0a5ceeb3dc8a22758cde0', // Replace if needed
         messagingSenderId: '593861404577', // Replace if needed
         projectId: 'plot-app-b8799', // Replace if needed
         authDomain: 'plot-app-b8799.firebaseapp.com', // Replace if needed
         storageBucket: 'plot-app-b8799.firebasestorage.app', // Replace if needed
         measurementId: 'G-JY24LSMSV1', // Replace if needed
       );
    }